### ISSUE TITLE
Add a Contributing.md

### ISSUE THREAD

**Issue by nlharris** [biolink/biolink-model#453] opened 2020-09-19 00:01 UTC
@justaddcoffee noted "Contributing.md - We have a "How to help" section in the Wiki that sort of serves this purpose. Possibly should flesh that out to address this." See also https://github.com/NCATS-Tangerine/kgx/

**Comment by sierra-moxon** [comment] 2021-06-11 16:17
duplicate of https://github.com/biolink/biolink-model/issues/267

**Closed by sierra-moxon** 2021-06-11 16:17 UTC
Labels: policy
