### ISSUE TITLE
Biolink model slot consistency and completeness

### ISSUE THREAD

**Issue by RichardBruskiewich** [biolink/biolink-model#243] opened 2019-07-02 23:00 UTC
While revisiting the parsing of the Biolink Model in our Knowledge Beacon code, it was surmised that the usage of some YAML attribute fields for classes and slots is possibly problematics. Here's a list:

1.  Some _class_  slots don't seem widely used: i.e. "values_from". "local_names", "subclass_of", "aliases" . "comments", "union_of", "alt_descriptions"?
2. What's the distinction between "comments" and "notes"?
3. The attribute "slot_usage" for many _category_ classes is both rare and has a somewhat  inconsistent format across entries
5. The attribute "slot_usage" for _association_ classes are a bit more consistent in allowed content but a bit inconsistent in the presence or absence of the three typical tags: subject, relation, object. Some associations have a handful of rare _ad hoc_ fields added in, e.g. "has <something>"; 'id', (maybe others...). The internal content of the 2nd level tags (e.g. subject, object) is also somewhat inconsistent (e.g. a few have id and examples, many don't?)

**Comment by hsolbrig** [comment] 2019-07-02 23:10
Item 2) The intended difference between comments and notes are that comments are intended to be semi-permanent and to accompany the artifact into the future, whilst notes are intended to be a spot for communication between editors (e.g. "todo...", "is this correct", ...).  Currently, `comments` is mapped comment to [skos:note](https://www.w3.org/TR/2009/REC-skos-reference-20090818/#notes) and `notes` to [skos:editorialNote](https://www.w3.org/TR/2009/REC-skos-reference-20090818/#notes)

**Comment by RichardBruskiewich** [comment] 2019-07-16 17:11
Thanks @hsolbrig for the feedback.

I guess I've not carefully scrutinised available guidelines for the field usage. It'll be an interesting challenge for us to educate the user (including curator) communities on the interpretation and best practices of the model field usage.

**Comment by deepakunni3** [comment] 2019-07-16 17:54
Yes, I agree with @RichardBruskiewich 
We should have a Curator/Contributor guideline document in the repo and refer potential users to that before changing the YAML.

**Comment by sierra-moxon** [comment] 2021-06-11 16:24
duplicate of #267

**Closed by sierra-moxon** 2021-06-11 16:24 UTC
Labels: QC, documentation, policy
