### ISSUE TITLE
Ensure all entries in derived json-ld context are complete and correct

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#223] opened 2019-06-10 18:15 UTC
* [ ] hANCESTRO now in OBO
 * [ ] Reactome should not be EXAMPLE
 * [ ] check other EXAMPLE entries
 * [ ] Add pubchem to YAML

**Comment by TomConlin** [comment] 2019-06-10 19:19
Where is this "json-ld context"  and how is it derived?

Reactome is :
 - 'REACT': 'http://www.reactome.org/PathwayBrowser/#/'

pubchem is:
 - 'CID': 'http://pubchem.ncbi.nlm.nih.gov/compound/'

**Comment by TomConlin** [comment] 2019-06-10 19:49
see also:
 https://github.com/biolink/biolink-model/commit/3d863790ce891fe3a5b00b31f5fbfefd32b41bcc#diff-c44fafd780b0fca86ebec1fdadaeca8b

**Comment by cmungall** [comment] 2019-06-11 15:13
> Where is this "json-ld context" and how is it derived?

There is minimal documentation we want to approve under "Identifiers" here:

https://biolink.github.io/biolink-model/

Note that everything in this repo other than the source yaml is derived, and you can always see the steps required in the Makefile:

https://github.com/biolink/biolink-model/blob/ad9ab3ad379e3a3c10fe6b12307c189e3c46ef82/Makefile#L86-L90

You should be able to run this locally.

**Comment by hsolbrig** [comment] 2019-06-11 16:23
https://biolink.github.io/biolinkml/context.jsonld


Harold Solbrig

**Comment by deepakunni3** [comment] 2020-07-06 22:07
Add to documentation/guide.

**Comment by RichardBruskiewich** [comment] 2020-08-05 17:53
@hsolbrig, I assume that you've fixed the correct CURIE prefix / URI for uniprot as in [biolinkml pull request 96](https://github.com/biolink/biolinkml/pull/96/commits/a585f88f75a539e84a19d13db41db27c42a6eadd) and for OMIM as in [biolinkml pull request 97](https://github.com/biolink/biolinkml/pull/97/commits/2e478655a84165bcf2d53f3f610f4354e476b572)?

I need to reread all the issue tips which tell hapless users like myself, exactly where the master "gold" standard strings for such CURIE prefix and URI's are are recorded in the Biolink Model...

**Comment by sierra-moxon** [comment] 2021-06-11 16:27
Most of the work on this ticket is done already. Except perhaps the documentation of this.  I am going to resolve it as a duplicate of the 'contributing' ticket #267

**Closed by sierra-moxon** 2021-06-11 16:27 UTC
Labels: QC, documentation
