### ISSUE TITLE
Split PubChem into PubChemCID and PubChemSID

### ISSUE THREAD

**Issue by nlharris** [biolink/biolink-model#424] opened 2020-08-19 19:45 UTC
**Is your feature request related to a problem? Please describe.**
 Don't use PubChem by itself as a prefix, but rather PubChem CID or SID. 

**What working group (or team) did this request originate from?**
Data Modeling

**Describe the solution you'd like**
Need to split PubChem into PubChemCID and PubChemSID.

**Comment by deepakunni3** [comment] 2020-08-19 21:02
Currently we have PUBCHEM.COMPOUND (PubChem CID) prefix listed for biolink:ChemicalSubstance and PUBCHEM.SUBSTANCE (Pubchem SID) prefix for biolink:Carbohydrate.

So I am assuming this issue is already been addressed. We can refine further by allowing PUBCHEM.SUBSTANCE be a valid prefix for biolink:ChemicalSubstance as well.

**Comment by nlharris** [comment] 2020-08-19 21:17
Tagging @vdancik (not sure that worked)

**Comment by deepakunni3** [comment] 2020-08-24 17:38
**Note:** remove `biolink:Carbohydrate`, `biolink:Drug`, `biolink:Metabolite` from the model. @deepakunni3

**Comment by vdancik** [comment] 2020-08-25 21:58
The most appropriate PubChem prefixes to use are "CID:" and "SID:" since these are already understood by PubChem: 

[https://pubchem.ncbi.nlm.nih.gov/CID:2244](https://pubchem.ncbi.nlm.nih.gov/CID:2244)

[https://pubchem.ncbi.nlm.nih.gov/ID:2244](https://pubchem.ncbi.nlm.nih.gov/SID:2244)

**Comment by vdancik** [comment] 2020-09-15 22:44
duplicate of #305

**Comment by nlharris** [comment] 2020-09-15 23:26
@vdancik you're right. Should we close that one, since this ticket has more information?

**Comment by nlharris** [comment] 2021-07-13 16:14
Vlado says this was addressed in Biolink 2.0 and can be closed.

**Closed** 2021-09-14 23:45 UTC
Labels: working-group/chemical, identifiers
