### ISSUE TITLE
Revisit UML displays

### ISSUE THREAD

**Issue by cmungall** [biolink/biolink-model#197] opened 2019-02-08 16:17 UTC
This looks pretty in an apoptosis kind of way:
https://biolink.github.io/biolink-model/docs/ChemicalSubstance.html

But is maybe not so useful

**Comment by cmungall** [comment] 2019-02-08 17:02
The UML may be partly simplified by: #198

**Comment by sierra-moxon** [comment] 2022-12-13 22:11
closing as a duplicate of #111

**Closed** 2022-12-13 22:12 UTC
Labels: enhancement, documentation
