### ISSUE TITLE
Clarify usage of Genotype and SequenceVariant, and possible new class (genopart)

### ISSUE THREAD

**Issue by kshefchek** [biolink/biolink-model#383] opened 2020-07-08 16:57 UTC
In Monarch we store sequence features that we neither categorize as genotypes or variants, ie genotype parts that are part_of|subClassOf [GENO:0000701](https://www.ebi.ac.uk/ols/ontologies/geno/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGENO_0000701)

Should we add a new biolink class for these, or add GENO:0000701 to GenomicEntity?

There are also entities like compound hets, which many might consider genotypes, for example https://www.ncbi.nlm.nih.gov/clinvar/variation/424707/ which we type as [GENO:0000402](https://www.ebi.ac.uk/ols/ontologies/geno/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGENO_0000402), which is a sequence feature attribute.  In the current model there is no way to infer a Biolink type from this, although perhaps this is incorrectly modelled and should be typed as some sequence feature set.

We could also make the case that any 'sequence feature set' is a genotype to more closely align with the clinical definition.

**Comment by cbizon** [comment] 2020-07-08 19:12
@mbrush is there room here to align with GA4GH as well?

**Comment by ehinderer** [comment] 2020-07-08 20:41
I'd like to lurk in this conversation. The Pathway Hypotheses Provider will need to know the best way to represent variant classes for genes where the sequence is absent. Right now it looks like SequenceVariant is most appropriate.

**Comment by monicacecilia** [comment] 2020-07-09 16:13
How about ```genotypic entity``` - to represent this?

**Comment by kshefchek** [comment] 2020-07-09 17:02
rereading the GENO genotype definition - I think the requirement for a genotype is a background reference genome, so with the compound het example, NM_018136.4(ASPM):c.10168C>T;NM_018136.4(ASPM):c8098C>T [GRCh38] is a proper genotype, whereas the coordinates (or two variant descriptions) without a reference is a genotype part (or genotypic entity).

**Comment by kshefchek** [comment] 2020-07-09 20:22
A proposal in https://github.com/biolink/biolink-model/pull/381

```
  genotypic entity:
    is_a: molecular entity
    aliases: ['sequence feature or set']
    description: >-
      A sequence feature or a set of such features. Includes sequence features not located on a genome such as gene knockdown reagents
    mappings:
      - GENO:0000701

  genomic entity:
    is_a: genotypic entity
```

**Comment by kshefchek** [comment] 2020-07-14 17:38
An alternative would be add [genomic feature set (GENO:0000660) ](https://www.ebi.ac.uk/ols/ontologies/geno/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGENO_0000660&viewMode=All&siblings=false) as a mapping for biolink:GenomicEntity, instead of adding a new class "genotypic entity".  I suspect sequence variant, genotype, and genomic entity will cover the majority of sequence feature modeling use cases in translator.

**Comment by deepakunni3** [comment] 2020-08-31 17:50
@cmungall Thoughts?

**Comment by kshefchek** [comment] 2020-08-31 18:01
for https://github.com/biolink/biolink-model/pull/381 I went with https://github.com/biolink/biolink-model/issues/383#issuecomment-658315408, I settled on having both genotypic entity and genotype is overkill for most use cases

**Comment by nlharris** [comment] 2020-10-19 23:14
So is there still work to do here or can this issue be closed?

**Comment by kshefchek** [comment] 2021-02-12 20:42
https://github.com/biolink/biolink-model/issues/383#issuecomment-658315408 is I went with here, I think GenomicEntity is enough resolution for our needs, but it would be good to get +1 (or -1) from @mbrush

**Comment by sierra-moxon** [comment] 2021-02-22 22:43
It sounds like @kshefchek and @mbrush have what they need (confirmed genomic entity (GENO:0000897)is a mapping for biolink:GenomicEntity). Closing. :)

**Closed by sierra-moxon** 2021-02-22 22:43 UTC
Labels: discussion
