### ISSUE TITLE
Biolink model website: named things are missing in overview

### ISSUE THREAD

**Issue by slobentanzer** [biolink/biolink-model#1144] opened 2022-11-07 17:35 UTC
**Describe the bug**
The class category "Named Thing" is not populated on the Website. https://biolink.github.io/biolink-model/docs/named_things.html

**Comment by nlharris** [comment] 2022-11-07 17:37
Closing as duplicate of #1081 
Thanks for reporting this (again); we'll try to look into it soon!

**Closed** 2022-11-07 17:39 UTC
Labels: documentation
